symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
  #    lifetime = délai de validité du lien de reset password, throttle limit = délai entre 2 demandes de reset
  #    password, garbage collection = quand true, supprime les demandes de reset expirées automatiquement.
    lifetime: 3600
    throttle_limit: 3600
    enable_garbage_collection: true